# The documentation for the contents of this file can be found at:
# https://docs.gitlab.com/ce/ci/yaml/README.html

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
# The recipe for this docker image can be found at:
# https://github.com/rust-lang/docker-rust/blob/267790f45f67986c1f5cec39206ba10a20df9624/1.51.0/buster/Dockerfile
image: "rust:1.51.0"

stages:
  - build
  - test

build-native:cargo:
  stage: build
  artifacts:
    paths:
      - target/
  script:
  - rustc --version && cargo --version
  - cargo build --lib --tests --verbose
  - cargo build --lib --tests --verbose --release

build-wasm32:cargo:
  stage: build
  script:
  - rustup target add wasm32-unknown-unknown
  - rustc --version && cargo --version
  - cargo build --target=wasm32-unknown-unknown --lib --tests --verbose
  - cargo build --target=wasm32-unknown-unknown --lib --tests --verbose --release

lint:clippy:
  stage: test
  dependencies:
    - build-native:cargo
  script:
  - rustup component add clippy
  - cargo clippy --all-targets --all-features -- -D warnings
